okta/okta-devices-swift

.github/workflows/okta_devices.yml

Build project with `build-for-testing` and reuse artifacts between Unit Tests, Functional Tests and Code Coverage with xcov

Improve CI by building once for tests and code coverage

---

Examples/PushSampleApp/SampleApp/PushNotificationService.swift
Examples/PushSampleApp/SampleApp/RootCoordinator.swift
Examples/PushSampleApp/SampleApp/UserConsent/UserConsentViewModel.swift

Checking by transactionID before presenting the user consent screen

Sample App - Avoid showing consent screen twice for same pending/push challenge

---

Sources/DeviceAuthenticator/Crypto/OktaBindJWT.swift

When approving an authentication request, the user doesn't necessarily know the source by referring to only the `iss` claim, as vanity urls aren't represented by that claim.
Expose the secondary claim `requestReferrer` that includes the vanity url, if necessary, to provide fuller context to the user.
Actual result:

Add requestReferrer to supported claims

---

Sources/DeviceAuthenticator/Storage/SQLite/OktaSharedSQLite.swift
Tests/DeviceAuthenticatorUnitTests/OktaSharedSQLiteTests.swift

For migration and for the future, adding a count method to retrieve count of enrollments without pulling all into memory.
Actual result:

Add enrollmentsCount method from sqlite

---

Podfile.lock
Sources/DeviceAuthenticator/DomainObjects/EnrollAuthenticatorRequestModel.swift
Sources/DeviceAuthenticator/Managers/OktaAuthenticatorsManager+Metadata.swift
Sources/DeviceAuthenticator/Networking/LegacyServerAPI.swift
Sources/DeviceAuthenticator/Networking/ServerAPIProtocol.swift
Sources/DeviceAuthenticator/Transactions/OktaTransactionEnroll+Factors.swift
Sources/DeviceAuthenticator/Transactions/OktaTransactionEnroll+Push.swift
Sources/DeviceAuthenticator/Transactions/OktaTransactionEnroll.swift
Tests/DeviceAuthenticatorUnitTests/AuthenticatorEnrollmentTests.swift
Tests/DeviceAuthenticatorUnitTests/EnrollAuthenticatorRequestModelTests.swift
Tests/DeviceAuthenticatorUnitTests/Mocks/RestAPIMock.swift
Tests/DeviceAuthenticatorUnitTests/OktaAuthenticatorsManagerTests.swift
Tests/DeviceAuthenticatorUnitTests/TransactionEnrollTests.swift

We need to move out API models building/parsing logic from enrollment transaction. In that case enrollment transaction impl will be server API agnostic
Note: unit test coverage for LegacyServerAPI class will be added in next PR
Actual result:

OKTA-540404 - Push SDK: Refactor enrollment flow in order to support different server APIs(legacy vs MyAccount)

---

Sources/DeviceAuthenticator/Networking/ServerErrorCodes.swift

Attempting to compare ServerErrorCodes results in `Operator function '==' requires that 'ServerErrorCode' conform to 'Equatable'`
Add Equatable protocol conformance to ServerErrorCode
`public enum ServerErrorCode: Codable, Equatable `
ServerErrorCode
Actual result: N/A
Expected result: N/A
N/A

Adds Equatable to ServerErrorCode

---

Sources/DeviceAuthenticator/Networking/LegacyServerAPI.swift

OV was broken due to recent MyAccount refactor. TOTP method was not being added to the list of Methods due to unnecessarily checking for the factor.keys on the totp enrollment and therefore OV was not showing any enrollment after adding an account.
Remove extra check for factor.keys since all Methods add this property since it's optional.
Actual result:

OKTA-543909 - Remove keys check when adding EnrollingFactors preventing TOTP methods to be added

---

Tests/DeviceAuthenticatorFunctionalTests/EnrollmentTestHelper.swift
Tests/DeviceAuthenticatorFunctionalTests/UpdateCIBAFlowTests.swift
Tests/DeviceAuthenticatorFunctionalTests/UpdatePushTokenFlowTests.swift
Tests/DeviceAuthenticatorUnitTests/Mocks/MockMultipleRequestsHTTPClient.swift

Since we don't have automations on real device to test push delivery we need to make sure that push token is always in expected format in http requests

Enhance tests to validate push token transformation in requests

---

Sources/DeviceAuthenticator/DeviceAuthenticatorError.swift
Sources/DeviceAuthenticator/Remediation/RemediationStepMessage.swift
Sources/DeviceAuthenticator/SecurityError.swift
Sources/DeviceAuthenticator/Transactions/OktaTransactionPossessionChallenge.swift
Sources/DeviceAuthenticator/Transactions/OktaUserConsentValue.swift

The SDK was ignoring LAError.authenticationFailed which caused biometric failures to trigger a fallback to simple UserConsent.
A new user consent value (`UV_TEMPORARILY_UNAVAILABLE`) was added and will be sent in cases where local authentication fails.
FP Challenges
1. Attempt FP authentication on macOS
2. Repeatedly use invalid fingerprint when prompted for biometrics.
Actual result: SDK falls back to using simple user consent
Expected result: SDK should abort authentication flow
I tested manually, but I didn't see a way to mock LAContext or the Keychain in the existing code. If I'm mistaken, or you'd like me to add a way, let me know.

Add `UV_TEMPORARILY_UNAVAILABLE` consent value

---

Sources/DeviceAuthenticator/Storage/OktaStorageManager.swift
Sources/DeviceAuthenticator/Storage/SQLite/OktaSQLIteConnectionBuilder.swift
Sources/DeviceAuthenticator/Storage/SQLite/OktaSharedSQLite.swift
Sources/DeviceAuthenticator/Storage/SQLite/SQLiteStorageVersion.swift

Add `configuration.busyMode = .timeout(1)` to sqlite configuration. This allows grdb to wait for 1 second before retrying in case if write operation returned SQLITE_BUSY error

OKTA-564428 - Add timeout configuration value for concurrent SQLIte requests to reduce probability of SQLITE_BUSY errors

---

Podfile.lock
Sources/DeviceAuthenticator/Networking/UserAgent.swift
Sources/DeviceAuthenticator/Utils/OktaBundleProperties.swift

- No team identifier produced for userAgent string on macOS.
- Full macOS version description produced for userAgent on macOS instead of short version string
**ProcessInfo.processInfo.operatingSystemVersionString** output is smth like **Version 12.6.2 (Build 21G320)), 12.6.2**
- Added [kSecUseDataProtectionKeychain](https://developer.apple.com/documentation/security/ksecusedataprotectionkeychain) key to the keychain query to obtain [kSecAttrAccessGroup](https://developer.apple.com/documentation/security/ksecattraccessgroup) value, which contains the team identifier.
- Invoke **ProcessInfo.processInfo.operatingSystemVersion** API to get all the OS version components and properly construct version string.

Fix missing teamIdentifier and incorrect OS version for userAgent string on macOS

---

Sources/DeviceAuthenticator/DeviceSignals/BasicSignalsHelper.swift

`uname()` function returns wrong device model value on macOS (`sysctl()`'s `"hw.machine"` instead of `"hw.model"`).
Replace `uname()` invocation with direct `sysctlbyname()` with correct parameter name value.
Actual result:
E2E on both iOS and macOS.

Return correct device model on macOS

---

Sources/DeviceAuthenticator/AuthenticatorEnrollmentProtocol.swift
Sources/DeviceAuthenticator/Enrollment/AuthenticatorEnrollment.swift
Sources/DeviceAuthenticator/Networking/ServerAPIProtocol.swift
Tests/DeviceAuthenticatorUnitTests/AuthenticatorEnrollmentTests.swift
Tests/DeviceAuthenticatorUnitTests/Mocks/RestAPIMock.swift
Tests/DeviceAuthenticatorUnitTests/MyAccountServerAPITests.swift

Add authorizationServerId parameter to retrieveMaintenanceToken API

Add authorizationServerId parameter to retrieveMaintenanceToken API

---

Sources/DeviceAuthenticator/AuthenticatorEnrollmentProtocol.swift
Sources/DeviceAuthenticator/Enrollment/AuthenticatorEnrollment.swift
Sources/DeviceAuthenticator/Networking/ServerAPIProtocol.swift
Tests/DeviceAuthenticatorUnitTests/AuthenticatorEnrollmentTests.swift
Tests/DeviceAuthenticatorUnitTests/Mocks/RestAPIMock.swift
Tests/DeviceAuthenticatorUnitTests/MyAccountServerAPITests.swift

Remove authorization server id from maintenance token API

Remove authorization server id from maintenance token API

---

Sources/DeviceAuthenticator/Networking/LegacyServerAPI.swift
Sources/DeviceAuthenticator/Networking/MyAccountServerAPI.swift
Sources/DeviceAuthenticator/Networking/ServerAPIProtocol.swift
Sources/DeviceAuthenticator/Transactions/OktaTransactionEnroll.swift
Tests/DeviceAuthenticatorUnitTests/AuthenticatorEnrollmentTests.swift
Tests/DeviceAuthenticatorUnitTests/LegacyServerAPITests.swift
Tests/DeviceAuthenticatorUnitTests/Mocks/RestAPIMock.swift
Tests/DeviceAuthenticatorUnitTests/MyAccountServerAPITests.swift
Tests/DeviceAuthenticatorUnitTests/TransactionEnrollTests.swift

UV key is always updated in patch request. That causes `Invalid Token Provided` issue when maintenance token is used
Use EnrollmentContext parameter to get the transaction settings

Fix unconditional update of UV key via patch request

---

Sources/DeviceAuthenticator/Transactions/OktaTransactionPullChallenge.swift
Tests/DeviceAuthenticatorUnitTests/TransactionPullChallengeTests.swift

Expose additional parameter in pending challenge callback to return all received challenges

Return all challenges as array for dictionaries via callback

---

Sources/DeviceAuthenticator/Crypto/OktaBindJWT.swift
Sources/DeviceAuthenticator/Enrollment/AuthenticatorEnrollment.swift
Sources/DeviceAuthenticator/Transactions/OktaTransaction.swift
Sources/DeviceAuthenticator/Transactions/OktaTransactionPossessionChallenge.swift
Sources/DeviceAuthenticator/Transactions/OktaTransactionPushChallenge.swift
Tests/DeviceAuthenticatorUnitTests/AuthenticatorEnrollmentTests.swift
Tests/DeviceAuthenticatorUnitTests/OktaTransactionPushChallengeTests.swift
Tests/DeviceAuthenticatorUnitTests/TransactionEnrollTests.swift
Tests/DeviceAuthenticatorUnitTests/TransactionPossessionChallengeBaseTests.swift
Tests/DeviceAuthenticatorUnitTests/TransactionTests.swift

Use bioOrPin key on ChallengeRequest handling and for enrollment deletion for end-to-end user experience using the passcode-capable key.

Enable bioOrPin key for authentications and enrollment deletion

---

Sources/DeviceAuthenticator/Storage/OktaSecureStorage.swift
Sources/DeviceAuthenticator/Storage/SQLite/OktaSQLiteEncryptionManager.swift

OktaSQLiteEncryptionManager has the following issues:
1. Requires OktaSecureStorage to be used. But OktaSecureStorage uses data protection keychain and hence in contexts where data protection keychain cannot be used, OktaSQLiteEncryptionManager cannot be used.
2. Requires keychain group id. But that is not applicable for macOS apps that don't use data protection keychain.
3. Defaults accessibility of the keychain item that holds encryption key to `kSecAttrAccessibleAfterFirstUnlock`. This can be ignored in a custom keychain helper classes but nevertheless forces a requirement that prevents access in pre-login contexts. 
1. Make the requirement for OktaSecureStorage a protocol requirement that OktaSecureStorage and other keychain helpers can conform to.
2. Make keychain group id optional …

Support SQLite encryption for macOS Desktop MFA

---

Sources/DeviceAuthenticator/DeviceSignals/DeviceSignals.swift
Sources/DeviceAuthenticator/DeviceSignals/iOS/OktaUnmangedDeviceSignals.swift
Tests/DeviceAuthenticatorUnitTests/OktaDeviceModelBuilderTests.swift
Tests/DeviceAuthenticatorUnitTests/OktaUnmanagedDeviceSignalsTests.swift

SDK should send signal values that are provided by the app without any fallback logic to default signals. One of the example is UDID property which SDK override with default value `UIDevice.current.identifierForVendor?.uuidString`
Don't override UDID property with default value, send value as-is

OKTA-610195 - Device SDK: Don't send AppInstanceID in UDID device property

---

Sources/DeviceAuthenticator/Storage/SQLite/OktaSharedSQLite.swift
Sources/DeviceAuthenticator/StorageVersioning/OktaStorageMigrator.swift
Tests/DeviceAuthenticatorUnitTests/OktaSharedSQLiteTests.swift

SDK fires exception when detects db version downgrade
Remove panic code from SQLite migration area where SDK rejects to initialize if db downgrade case has been detected
Device SDK will make the best effort to continue to work with existing version of db
OktaSharedSQLite.swift

OKTA-611592 - Device SDK: Add version downgrade support fro sqlite db

---

Sources/DeviceAuthenticator/Enrollment/AuthenticatorEnrollment.swift
Sources/DeviceAuthenticator/Storage/OktaEnrollmentStorageProtocol.swift
Sources/DeviceAuthenticator/Storage/OktaStorageManager.swift
Sources/DeviceAuthenticator/Storage/SQLite/OktaSharedSQLite.swift
Tests/DeviceAuthenticatorUnitTests/Mocks/StorageManagerMock.swift
Tests/DeviceAuthenticatorUnitTests/OktaSharedSQLiteTests.swift

We store full enrollment just to update one flag on enrollment level
Introduce a separate API for storing server error code

Store server error code via a separate storage API

---

Sources/DeviceAuthenticator/Transactions/OktaTransactionEnroll.swift

At enrollment time, the device id is used to prevent duplicate enrollments from the same device. Previously, the device id was not being sent for new enrollments.
Adding the device id for all enrollment operations allows the Okta backend to detect and de-duplicate these conflicting enrollments.

Add DeviceId to all enrollment operations

---

Sources/DeviceAuthenticator/ApplicationConfig.swift
Sources/DeviceAuthenticator/DeviceAuthenticatorError.swift
Sources/DeviceAuthenticator/DeviceSignals/OktaDeviceModelBuilder.swift
Sources/DeviceAuthenticator/Enrollment/OktaApplicationInfo.swift
Sources/DeviceAuthenticator/Networking/DeviceSignalsModel.swift
Tests/DeviceAuthenticatorUnitTests/OktaDeviceModelBuilderTests.swift

Duplicate enrollments in case of timed-out enrollment requests
Send `authenticatorAppKey` in signals payload. Signal uniquely identifies the device while application is installed

OKTA-622047 - Push SDK: Send authenticatorAppKey in Device payload

---

Sources/DeviceAuthenticator/Transactions/OktaTransactionPossessionChallenge.swift

Excessive logging of the same error.
Remove duplicate logging. The error if occurred is printed in [readSigningKey](https://github.com/okta/okta-devices-swift/blob/c818691399757639dfa0b8cb2effd1b0ad74c3b6/Sources/DeviceAuthenticator/Transactions/OktaTransactionPossessionChallenge.swift#L251)

Remove duplicate error logging if no key tag for provided key type found

---

Sources/DeviceAuthenticator/Enrollment/AuthenticatorEnrollment.swift
Sources/DeviceAuthenticator/Transactions/OktaTransactionEnroll.swift
Tests/DeviceAuthenticatorUnitTests/AuthenticatorEnrollmentTests.swift

… all factors and key health
Currently logic only checks for tag presence and doesn't check any other factors or keys
Enumerate all factors and check key health, then use the key for jwt signing

OKTA-646550 - iOS Device SDK: Redo ssws token generation logic to take into account key health

---

Podfile.lock
Sources/DeviceAuthenticator/DeviceSignals/OktaDeviceModelBuilder.swift
Tests/DeviceAuthenticatorUnitTests/OktaDeviceModelBuilderTests.swift

Server rejects device key reenroll request
In order to successfully reenroll device key when device key is not available we need to provide deviceModel.id and deviceModel.clientInstanceId in device payload

Include device.id and clientInstanceId into update device payload

---

Sources/DeviceAuthenticator/Crypto/OktaDeviceBindJWTPayload.swift
Sources/DeviceAuthenticator/Networking/DeviceSignalsModel.swift

Need to log certain 1st party properties and hide others.
Conform DeviceSignalsModel to CustomStringConvertible so we can customize it's description.
Output after printing object:
`2023-09-18 19:00:35.912621-0400 Okta Verify[1859:843208] {✅ "AsyncSignals": {"message": "First party signals collected: , platform: Optional(OktaDeviceSDK.PlatformValue.iOS), osVersion: Optional("16.6.1"), displayName: <REDACTED>, id: <REDACTED>, manufacturer: Optional("APPLE"), model: Optional("iPhone10,3"), serialNumber: <REDACTED>, udid: <REDACTED>, meid: <REDACTED>, imei: <REDACTED>, sid: <REDACTED>, secureHardwarePresent: Optional(true), screenLockType: Optional(OktaDeviceSDK.ScreenLockValue.biometric), diskEncryptionType: Optional(OktaDeviceSDK.DiskEncryptionValue.full), deviceAttestation: <REDACTED>, …

OKTA-648357 - Conform DeviceSignalsModel to CustomStringConvertible

---

Sources/DeviceAuthenticator/Transactions/OktaTransactionEnroll.swift
Tests/DeviceAuthenticatorUnitTests/TransactionEnrollTests.swift

- Re-enrollment fails when device was deleted by admin.
- Retry with no deviceEnrollment if backend returns deviceDeleted.
- Verified fix with multiple accounts on the same org.
Actual result:

OKTA-643877 - Retry with no deviceId if backend returns .deviceDeleted

---

Sources/DeviceAuthenticator/DeviceSignals/macOS/FileTypeSignalPluginManager.swift

Currently, String(contentsOf:) is used which causes double-conversion to and from data. The underlying mechanism is not defined, meaning that using String() when the file is being written to may have unknown consequences.
Using Data(contentsOf:) allows to skip reading to memory twice and prevents .utf8 conversion. This should improve with consistency and reliability as well as performance.
Actual result:

OKTA-652751: Use Data for pulling from file signal

---

Sources/DeviceAuthenticator/DeviceSignals/OktaDeviceModelBuilder.swift
Sources/DeviceAuthenticator/Transactions/OktaTransactionEnroll.swift
Tests/DeviceAuthenticatorFunctionalTests/EnrollmentFlowTests.swift
Tests/DeviceAuthenticatorUnitTests/OktaDeviceModelBuilderTests.swift

In backup and restore use cases users are struggling to reenroll since stale data affects enrollment process
- Don't re-use same device id and clientInstanceId for new device enrollment since in most case it is new device(backup and restore)
- Important piece here is appAuthenticatorId device signal which may give a hint to server whether to create new object or re-use same device
Enroll transaction
Added functional tests

Recreate device object on server side if client fails to build client instance key attestation

---

Examples/PushSampleApp/Podfile.lock
Examples/PushSampleApp/SampleApp.xcodeproj/project.pbxproj
Examples/PushSampleApp/SampleApp.xcworkspace/xcshareddata/swiftpm/Package.resolved
Examples/PushSampleApp/SampleApp/Extensions+Utils/OktaWebAuthProtocol.swift
Examples/PushSampleApp/SampleApp/WebSignIn/SignInViewModel.swift

Sample app was failing to build.
WebAuth SDK updated recently and we were not pinning to any version in SPM. Now we pinned to 1.4.3 and upToNextMajorVersion.
Actual result:

Update OktaWebAuthProtocol to conform to latest WebAuth SDK methods.

---

Sources/DeviceAuthenticator/Storage/SQLite/OktaSharedSQLite.swift

SDK leaves stale enrollment data when detects duplicate enrollment during save operation
- Remove enrollment data as well when duplicate enrollment is detected
- Search duplicate by enrollmentId instead of orgI+userId combo

Backport enrollment override fix from OV codebase
