- DeviceAuthenticator.xcodeproj/project.pbxproj
- Sources/DeviceAuthenticator/Enrollment/DeviceAuthenticator.swift
- Sources/DeviceAuthenticator/Networking/LegacyServerAPI.swift
- Sources/DeviceAuthenticator/Networking/ServerAPIProtocol.swift
- Sources/DeviceAuthenticator/Transactions/OktaTransactionEnroll.swift
- Sources/DeviceAuthenticator/Transactions/OktaTransactionPushTokenUpdate.swift
- Tests/DeviceAuthenticatorFunctionalTests/EnrollmentFlowTests.swift
- Tests/DeviceAuthenticatorFunctionalTests/EnrollmentTestHelper.swift
- Tests/DeviceAuthenticatorUnitTests/AuthenticatorEnrollmentTests.swift
- Tests/DeviceAuthenticatorUnitTests/AuthenticatorObjectTests.swift
- Tests/DeviceAuthenticatorUnitTests/LegacyServerAPITests.swift
- Tests/DeviceAuthenticatorUnitTests/Mocks/GoldenData.swift
- Tests/DeviceAuthenticatorUnitTests/Mocks/RestAPIMock.swift
- Tests/DeviceAuthenticatorUnitTests/OktaAuthenticatorsManagerTests.swift
- Tests/DeviceAuthenticatorUnitTests/OktaFactorPushTests.swift
- Tests/DeviceAuthenticatorUnitTests/OktaFactorTests.swift
- Tests/DeviceAuthenticatorUnitTests/TransactionEnrollTests.swift
- Tests/DeviceAuthenticatorUnitTests/TransactionPullChallengeTests.swift
Enrollment transaction is tightly coupled with request/response models
Refactor enrollment transaction so it is not tightly coupled with request/response models
Actual result:
> Refactor enrollment response

- Sources/DeviceAuthenticator/Networking/LegacyServerAPI.swift
Metadata is required for signed_nonce and totp factors
> Pass metadata for factor creation methods

- README.md
> OKTA-535220 - Add tMFA readme changes

- DeviceAuthenticator.xcodeproj/project.pbxproj
- Sources/DeviceAuthenticator/Enrollment/AuthenticatorEnrollment.swift
- Sources/DeviceAuthenticator/Networking/AuthenticatorResponseModel.swift
- Sources/DeviceAuthenticator/Networking/CapabilitiesModel.swift
- Sources/DeviceAuthenticator/Networking/EnrollAuthenticatorRequestModel.swift
- Sources/DeviceAuthenticator/Networking/LegacyServerAPI.swift
- Sources/DeviceAuthenticator/Networking/MethodUpdateRequestModel.swift
- Sources/DeviceAuthenticator/Networking/MyAccountServerAPI.swift
- Sources/DeviceAuthenticator/Networking/ServerAPIProtocol.swift
- Sources/DeviceAuthenticator/Networking/SigningKeysModel.swift
- Sources/DeviceAuthenticator/Transactions/OktaTransactionEnroll+Push.swift
- Sources/DeviceAuthenticator/Transactions/OktaTransactionEnroll.swift
- Sources/DeviceAuthenticator/Transactions/OktaTransactionPushTokenUpdate.swift
- Tests/DeviceAuthenticatorUnitTests/LegacyServerAPITests.swift
- Tests/DeviceAuthenticatorUnitTests/Mocks/GoldenData.swift
- Tests/DeviceAuthenticatorUnitTests/MyAccountServerAPITests.swift
> Http patch support for user verification, push token update and CIBA operations

- Sources/DeviceAuthenticator/Networking/LegacyServerAPI.swift
- Sources/DeviceAuthenticator/Networking/MyAccountServerAPI.swift
- Sources/DeviceAuthenticator/Networking/ServerAPIProtocol.swift
- Sources/DeviceAuthenticator/Transactions/OktaTransactionPullChallenge.swift
- Tests/DeviceAuthenticatorUnitTests/LegacyServerAPITests.swift
- Tests/DeviceAuthenticatorUnitTests/Mocks/RestAPIMock.swift
- Tests/DeviceAuthenticatorUnitTests/MyAccountServerAPITests.swift
Implement Pending challenge and Delete APIs
> Implement pending and delete MyAccount APIs

- Examples/PushSampleApp/Podfile.lock
- Examples/PushSampleApp/SampleApp/Okta.plist
- Sources/DeviceAuthenticator/Enrollment/DeviceAuthenticator.swift
- Sources/DeviceAuthenticator/Networking/LegacyServerAPI.swift
- Sources/DeviceAuthenticator/Networking/MyAccountAPI.swift
- Sources/DeviceAuthenticator/Networking/MyAccountServerAPI.swift
- Sources/DeviceAuthenticator/Networking/ServerAPIProtocol.swift
- Sources/DeviceAuthenticator/Transactions/OktaTransactionDeleteEnrollment.swift
- Tests/DeviceAuthenticatorUnitTests/LegacyServerAPITests.swift
- Tests/DeviceAuthenticatorUnitTests/Mocks/GoldenData.swift
- Tests/DeviceAuthenticatorUnitTests/Mocks/RestAPIMock.swift
- Tests/DeviceAuthenticatorUnitTests/MyAccountServerAPITests.swift
SDK fixes based on MyAccount API testing results
> OKTA-538932 - iOS QA GA testing on MyAccount api

- Tests/DeviceAuthenticatorFunctionalTests/VerifyFlowTests.swift
Functional test for Deny challenge
Actual result:
> OKTA-545115 - Add missing functional test for CIBA

- README.md
> OKTA-539691 - Add info for device name in README

- Sources/DeviceAuthenticator/Networking/MyAccountServerAPI.swift
- Tests/DeviceAuthenticatorFunctionalTests/DeleteEnrollmentFlowTests.swift
- Tests/DeviceAuthenticatorFunctionalTests/EnrollmentFlowTests.swift
- Tests/DeviceAuthenticatorFunctionalTests/EnrollmentTestHelper.swift
- Tests/DeviceAuthenticatorFunctionalTests/UpdateCIBAFlowTests.swift
- Tests/DeviceAuthenticatorFunctionalTests/UpdatePushTokenFlowTests.swift
- Tests/DeviceAuthenticatorFunctionalTests/UserVerificationFlowTests.swift
- Tests/DeviceAuthenticatorFunctionalTests/VerifyFlowTests.swift
- Tests/DeviceAuthenticatorUnitTests/Mocks/GoldenData.swift
Fix functional tests to work with MyAccount API
> Fix functional tests to work with MyAccount API

- Sources/DeviceAuthenticator/Crypto/OktaBindJWT.swift
- Sources/DeviceAuthenticator/Transactions/OktaTransactionPossessionChallenge.swift
- Tests/DeviceAuthenticatorUnitTests/OktaDeviceBindJWTTests.swift
…nge Request JWT
Remove deprecated claim `keyTypes` from challenge request
> OKTA-555682 - FixIt iOS: Cleanup deprecated values from Device Challenge Request JWT

- Sources/DeviceAuthenticator/Enrollment/DeviceAuthenticator.swift
- Sources/DeviceAuthenticator/Networking/MyAccountServerAPI.swift
- Tests/DeviceAuthenticatorFunctionalTests/DeleteEnrollmentFlowTests.swift
- Tests/DeviceAuthenticatorFunctionalTests/EnrollmentFlowTests.swift
- Tests/DeviceAuthenticatorFunctionalTests/EnrollmentTestHelper.swift
- Tests/DeviceAuthenticatorFunctionalTests/UpdateCIBAFlowTests.swift
- Tests/DeviceAuthenticatorFunctionalTests/UpdatePushTokenFlowTests.swift
- Tests/DeviceAuthenticatorFunctionalTests/UserVerificationFlowTests.swift
- Tests/DeviceAuthenticatorFunctionalTests/VerifyFlowTests.swift
- Tests/DeviceAuthenticatorUnitTests/Mocks/GoldenData.swift
This reverts commit 36d6bf3f928e13c4f5c1edf957deb922ac7a3d7e.
Revert impl to use legacy API
> Revert "Fix functional tests to work with MyAccount API (#81)"

- README.md
- Sources/DeviceAuthenticator/Transactions/OktaTransactionEnroll+Factors.swift
- Sources/DeviceAuthenticator/Transactions/OktaTransactionEnroll+Push.swift
- Tests/DeviceAuthenticatorFunctionalTests/UserVerificationFlowTests.swift
- Tests/DeviceAuthenticatorUnitTests/Mocks/GoldenData.swift
Update flow resets ciba setting for enrollment to `.login` value
> OKTA-560809 - User verification enrollment affects CIBA property

- Sources/DeviceAuthenticator/Networking/MyAccountAPI.swift
- Sources/DeviceAuthenticator/Networking/MyAccountServerAPI.swift
- Tests/DeviceAuthenticatorUnitTests/AuthenticatorObjectTests.swift
- Tests/DeviceAuthenticatorUnitTests/Mocks/GoldenData.swift
- Tests/DeviceAuthenticatorUnitTests/MyAccountServerAPITests.swift
- Fixed enrollment link naming
- Added parsing of `self` links
> Fixed enrollment link naming

- DeviceAuthenticator.xcodeproj/project.pbxproj
- Sources/DeviceAuthenticator/Storage/SQLite/OktaSQLitePersistentStorage.swift
- Sources/DeviceAuthenticator/Storage/SQLite/SQLiteStorageVersion.swift
- Sources/DeviceAuthenticator/Storage/SQLite/schemas/SQLiteSchemaBase.swift
- Sources/DeviceAuthenticator/Storage/SQLite/schemas/SQLiteSchemaMigration_v2.swift
- Sources/DeviceAuthenticator/StorageVersioning/OktaStorageMigrator.swift
- Tests/DeviceAuthenticatorUnitTests/OktaSharedSQLiteTests.swift
Define process for internal sqlite migrations
Defining new schema version should be as easy as applying delta changes for known N-1 version schema
> Define process for internal sqlite migrations

- Sources/DeviceAuthenticator/Transactions/OktaTransactionPossessionChallenge.swift
- Sources/DeviceAuthenticator/Transactions/OktaUserConsentValue.swift
- Tests/DeviceAuthenticatorUnitTests/TransactionPossessionChallengeBaseTests.swift
Handle UV_PERMANENTLY_UNAVAILABLE value
> OKTA-522855 - iOS: Handle new UserConsent values

- DeviceAuthenticator.xcodeproj/project.pbxproj
- Podfile.lock
- Sources/DeviceAuthenticator/AuthenticatorEnrollmentProtocol.swift
- Sources/DeviceAuthenticator/Crypto/OktaBearerJWTAssertion.swift
- Sources/DeviceAuthenticator/Crypto/OktaJWTGenerator.swift
- Sources/DeviceAuthenticator/Enrollment/AuthenticatorEnrollment.swift
- Sources/DeviceAuthenticator/Enrollment/OktaFactor.swift
- Sources/DeviceAuthenticator/Enrollment/OktaFactorPush.swift
- Sources/DeviceAuthenticator/Networking/Oauth2Credential.swift
- Sources/DeviceAuthenticator/Networking/ServerAPIProtocol.swift
- Tests/DeviceAuthenticatorUnitTests/AuthenticatorEnrollmentTests.swift
- Tests/DeviceAuthenticatorUnitTests/Mocks/GoldenData.swift
- Tests/DeviceAuthenticatorUnitTests/Mocks/RestAPIMock.swift
- Tests/DeviceAuthenticatorUnitTests/Mocks/TestUtils.swift
- Tests/DeviceAuthenticatorUnitTests/MyAccountServerAPITests.swift
- Tests/DeviceAuthenticatorUnitTests/OktaFactorTests.swift
- JWT-Bearer grant type network API implementation
- retrieveMaintenanceToken API implementation
> OKTA-571100 - Devices SDK: iOS JWT Bearer

- Sources/DeviceAuthenticator/Enrollment/DeviceAuthenticator.swift
- Sources/DeviceAuthenticator/Networking/MyAccountServerAPI.swift
- Tests/DeviceAuthenticatorFunctionalTests/DeleteEnrollmentFlowTests.swift
- Tests/DeviceAuthenticatorFunctionalTests/EnrollmentFlowTests.swift
- Tests/DeviceAuthenticatorFunctionalTests/EnrollmentTestHelper.swift
- Tests/DeviceAuthenticatorFunctionalTests/UpdateCIBAFlowTests.swift
- Tests/DeviceAuthenticatorFunctionalTests/UpdatePushTokenFlowTests.swift
- Tests/DeviceAuthenticatorFunctionalTests/UserVerificationFlowTests.swift
- Tests/DeviceAuthenticatorFunctionalTests/VerifyFlowTests.swift
- Tests/DeviceAuthenticatorUnitTests/Mocks/GoldenData.swift
> Restore MyAccount tests

- Examples/PushSampleApp/Podfile.lock
- Examples/PushSampleApp/SampleApp.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Examples/PushSampleApp/SampleApp/Extensions+Utils/OktaWebAuthProtocol.swift
- Examples/PushSampleApp/SampleApp/Okta.plist
- Examples/PushSampleApp/SampleApp/PushNotificationService.swift
- Examples/PushSampleApp/SampleApp/Settings/SettingsViewModel.swift
- Sources/DeviceAuthenticator/Networking/Oauth2Credential.swift
- Sources/DeviceAuthenticator/Networking/ServerAPIProtocol.swift
- Tests/DeviceAuthenticatorUnitTests/AuthenticatorEnrollmentTests.swift
- Tests/DeviceAuthenticatorUnitTests/Mocks/GoldenData.swift
- Tests/DeviceAuthenticatorUnitTests/MyAccountServerAPITests.swift
Show usage of retrieveMaintenanceToken API in sample app
> Show usage of retrieveMaintenanceToken API in sample app

- DeviceAuthenticator.xcodeproj/project.pbxproj
- Examples/PushSampleApp/README.md
- Examples/PushSampleApp/SampleApp.xcodeproj/project.pbxproj
- Examples/PushSampleApp/SampleApp/AppDelegate.swift
- Examples/PushSampleApp/SampleApp/Extensions+Utils/OktaWebAuthProtocol.swift
- Examples/PushSampleApp/SampleApp/RootCoordinator.swift
- Update readme
- Unconditionally remove credential even if sign-out fails
> Sample app update

- Examples/PushSampleApp/SampleApp/PushNotificationService.swift
- Sources/DeviceAuthenticator/Transactions/OktaTransactionEnroll+Push.swift
- Sources/DeviceAuthenticator/Transactions/OktaTransactionEnroll.swift
- Sources/DeviceAuthenticator/Transactions/OktaTransactionPushTokenUpdate.swift
- Update sample app logic around sending device token to server
- Remove deprecated functions saveDeviceToken and readDeviceToken in OktaTransactionEnroll class
> OKTA-586016 - Sample App: push notification is not received when a user login for the first time

- README.md
Document `retrieveMaintenanceToken` API usage
> Document `retrieveMaintenanceToken` usage

- Sources/DeviceAuthenticator/Transactions/OktaTransactionPossessionChallenge.swift
Remove private accessibility specificator for challengeContext function so it can be override in child classes
> Make challengeContext overridable

- Sources/DeviceAuthenticator/Crypto/OktaRequestJWTGenerator.swift
- Sources/DeviceAuthenticator/Enrollment/AuthenticatorEnrollment.swift
- Sources/DeviceAuthenticator/Transactions/OktaTransactionPullChallenge.swift
- Tests/DeviceAuthenticatorFunctionalTests/VerifyFlowTests.swift
- Tests/DeviceAuthenticatorUnitTests/AuthenticatorEnrollmentTests.swift
- Tests/DeviceAuthenticatorUnitTests/Mocks/TestUtils.swift
- Tests/DeviceAuthenticatorUnitTests/TransactionPullChallengeTests.swift
Implement function for generating SSWS token on enrollment level
> OKTA-598268 - iOS Push SDK: Implement function for generating SSWS token

- Sources/DeviceAuthenticator/Crypto/OktaDeviceBindJWTPayload.swift
- Tests/DeviceAuthenticatorUnitTests/OktaDeviceBindJWTTests.swift
Some potentially sensitive items were being logged to a readable file by some consumers of the SDK.
This change redacts additional items in the Device challenge payload which could potentially contain sensitive information, given that they are produced by 3rd party integrations.
- Redact Managment attestation JWTs (remove device attestation key from allowlist)
- Redact signalProvider and Integration details by adding another layer of allow list (to preserve debuggability)
OktaDeviceBindJWTPayload
> Redact Additional items from device challenge payload

- Sources/DeviceAuthenticator/StorageVersioning/OktaStorageMigrator.swift
- Tests/DeviceAuthenticatorUnitTests/OktaSharedSQLiteTests.swift
Handle `unknown` db version: Allow Device SDK to work with the db in that case
> Handle unknown version of db schema

- Sources/DeviceAuthenticator/Networking/LegacyServerAPI.swift
> OKTA-613912: Better logging of enrolled keys

- DeviceAuthenticator.xcodeproj/project.pbxproj
- Sources/DeviceAuthenticator/Networking/MyAccountAPI.swift
- Sources/DeviceAuthenticator/Networking/SigningKeysModel.swift
- Tests/DeviceAuthenticatorFunctionalTests/DeleteEnrollmentFlowTests.swift
- Tests/DeviceAuthenticatorFunctionalTests/EnrollmentFlowTests.swift
- Tests/DeviceAuthenticatorFunctionalTests/FunctionalTestsBase.swift
- Tests/DeviceAuthenticatorFunctionalTests/UpdateCIBAFlowTests.swift
- Tests/DeviceAuthenticatorFunctionalTests/UpdatePushTokenFlowTests.swift
- Tests/DeviceAuthenticatorFunctionalTests/UserVerificationFlowTests.swift
- Tests/DeviceAuthenticatorFunctionalTests/VerifyFlowTests.swift
- Tests/DeviceAuthenticatorUnitTests/Mocks/SecKeyHelperMock.swift
- Tests/DeviceAuthenticatorUnitTests/OktaAuthenticationJWTGeneratorTests.swift
- Tests/DeviceAuthenticatorUnitTests/OktaSharedSQLiteTests.swift
Scope of changes:
- Implement testMultipleEnrollmentsOnTheSameOrg test
- Remove db before each functional test starts
- Remove code duplication in tests
> Implement functional test for multi account scenarios

- .circleci/config.yml
Ticket - https://oktainc.atlassian.net/browse/OKTA-624438
https://app.circleci.com/pipelines/github/okta/okta-devices-swift/80/workflows/94172611-4e0f-4090-9f64-a9b84dba7478/jobs/314
> Add software dependency scans to the build

- Sources/DeviceAuthenticator/Transactions/OktaTransaction.swift
Change type of enrollment property to avoid downcast in other layers
> Change type of enrollment property to avoid downcast in other layers

- Sources/DeviceAuthenticator/Transactions/OktaTransaction.swift
- Sources/DeviceAuthenticator/Transactions/OktaTransactionPossessionChallenge.swift
- Sources/DeviceAuthenticator/Transactions/OktaTransactionPushChallenge.swift
- Sources/DeviceAuthenticator/Transactions/PushChallenge.swift
- Tests/DeviceAuthenticatorUnitTests/Mocks/RestAPIMock.swift
- Tests/DeviceAuthenticatorUnitTests/OktaTransactionPushChallengeTests.swift
- Tests/DeviceAuthenticatorUnitTests/TransactionPossessionChallengeBaseTests.swift
This reverts commit 56c67477d7edb0e959bee9941fe43d936bddbcf7.
> Revert "Temporary revert refactoring work to accommodate OV HF (#155)"

- Sources/DeviceAuthenticator/Enrollment/DeviceAuthenticator.swift
- Sources/DeviceAuthenticator/Managers/_OktaAuthenticatorsManager.swift
- Tests/DeviceAuthenticatorFunctionalTests/EnrollmentFlowTests.swift
- Tests/DeviceAuthenticatorUnitTests/OktaAuthenticatorsManagerTests.swift
Make storageManager property as optional
OV specific changes to make application start more reliable and crash-free
> Make storageManager as optional property

- Sources/DeviceAuthenticator/DeviceSignals/OktaDeviceModelBuilder.swift
- Tests/DeviceAuthenticatorUnitTests/Mocks/OktaDeviceBindJWTPartialMock.swift
Build fails due to missing UIKit import
Import UIKit
Actual result:
> OKTA-677650 - Explicitly import UIKit
